name: Nova APK Gyartas ES Firebase Kulcs

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kod lekerese
      uses: actions/checkout@v4

    - name: Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle beallitasa
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.4'

    # EZ A MODUL LEGYÁRTJA NEKÜNK A TITKOS KULCSOT A FELHŐBEN!
    - name: Hivatalos Android Keystore Generealas
      run: |
        keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=NovaZene, OU=Android, O=Hangfolyam, L=Budapest, S=Pest, C=HU" -storepass android -keypass android
        echo "A FIREBASE-BE EZT AZ SHA-1 KÓDOT KELL BEMÁSOLNOD:"
        keytool -list -v -keystore my-release-key.keystore -alias my-key-alias -storepass android -keypass android | grep "SHA1:"

    - name: APK epitese
      run: gradle :app:assembleDebug

    - name: Letoltes letrehozasa
      uses: actions/upload-artifact@v4
      with:
        name: Nova-Zene-APK
        path: app/build/outputs/apk/debug/app-debug.apk
